import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { api } from "~/utils/api";
import { env } from "~/env.mjs";

const CommunityPage: NextPage = () => {
  const { data: icons } = api.icons.getCommunityIcons.useQuery();

  return (
    <>
      <Head>
        <title>Community Icons</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto mt-24 flex min-h-screen flex-col gap-4 px-8">
        <h1 className="text-4xl">Your Icons</h1>
        <ul className="xs:grid-cols-4 grid grid-cols-2 gap-4 md:grid-cols-6">
          {icons
            ? icons.map((icon) => (
                <li key={icon.id}>
                  <Image
                    className="w-full rounded-lg"
                    src={`https://${env.NEXT_PUBLIC_AWS_BUCKET_NAME}.s3.eu-north-1.amazonaws.com/${icon.id}`}
                    alt={icon.prompt ?? "Icon generated from Prompt"}
                    width={100}
                    height={100}
                  />
                </li>
              ))
            : "You dont have any icons"}
        </ul>
      </main>
    </>
  );
};

export default CommunityPage;
